author:
  firstname: Cameron
  surname: Dias-Doyle
  fullname: Cameron Dias-Doyle
  dateofbirth: 1992-02-17 00:00:00 +0000
  location: Edinburgh, Scotland
  employer: FanDuel
  email: hello@camerondoyle.co.uk

header_settings:
  logo_image: 

menu_settings:
  menu_items:
    - title: 'Experience'
      url: '/experience'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Now'
      url: '/now/'
    # - title: 'Contact'
    #   url: '/contact'

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/cameron.diasdoyle'
  instagram_url: 'https://www.instagram.com/charlie.border.collie'
  github_url: 'https://github.com/CameronD17'
